# Generated by Django 4.2.2 on 2023-06-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productspecification_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='product_type',
        ),
    ]
